# Generated by Django 4.0.4 on 2022-05-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('comment', '0002_forum_comment_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum_comment',
            name='forum_id',
        ),
        migrations.AddField(
            model_name='forum_comment',
            name='ForumPost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forum.forum_post'),
        ),
    ]
