# Generated by Django 4.0.4 on 2022-05-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_forum_comment_forum_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum_comment',
            old_name='ForumPost',
            new_name='forumpost',
        ),
        migrations.RemoveField(
            model_name='forum_comment',
            name='image',
        ),
    ]
