# Generated by Django 4.0.4 on 2022-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
