# Generated by Django 4.0.4 on 2022-05-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_content_forum_post_description'),
        ('comment', '0006_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_comment',
            name='forumpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forum_post'),
        ),
    ]
