# Generated by Django 4.0.4 on 2022-05-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_forum_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum_comment',
            name='date',
        ),
    ]
