# Generated by Django 4.0.4 on 2022-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_remove_forum_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_comment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
