# Generated by Django 4.0.4 on 2022-05-20 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_admin'),
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_reply',
            name='forumcomment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comment.forum_comment'),
        ),
    ]
