# Generated by Django 4.0.4 on 2022-05-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_delete_admin'),
        ('reply', '0003_remove_forum_reply_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_reply',
            name='forumcomment',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.forum_comment'),
        ),
    ]
