# Generated by Django 4.0.4 on 2022-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0005_alter_forum_reply_forumcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_reply',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
