# Generated by Django 4.0.4 on 2022-05-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum_post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='forum_post',
            name='post_id',
        ),
    ]
