# Generated by Django 4.0.4 on 2022-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_post_image_remove_forum_post_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum_post',
            old_name='content',
            new_name='description',
        ),
    ]
