# Generated by Django 4.0.4 on 2022-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forum_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
